- name: Decrypt passwords
  hosts: localhost
  gather_facts: false
  vars:
    CONFIG_DIR: ""
    list_sops_files: []
  tasks:
    - name: Check that files are still not encrypted
      command: grep -qs 'sops:\|"sops":\|\[sops\]\|sops_version=' "{{ CONFIG_DIR }}/{{ item }}"
      register: encrypted_files_result
      failed_when: encrypted_files_result.rc == 0
      loop: "{{ list_sops_files }}"
  tags: always
